// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVqonFsnt6vVko252ixejqXNhtPHmgvQc',
    appId: '1:798737752380:web:b07efe3757b71cc7173e39',
    messagingSenderId: '798737752380',
    projectId: 'henry-store-94b54',
    authDomain: 'henry-store-94b54.firebaseapp.com',
    storageBucket: 'henry-store-94b54.appspot.com',
    measurementId: 'G-Z5JXT6TEGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJrJNPY84s1AycRlshd1aBTHz3kWAIUsM',
    appId: '1:798737752380:android:3b7b916338349f7d173e39',
    messagingSenderId: '798737752380',
    projectId: 'henry-store-94b54',
    storageBucket: 'henry-store-94b54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk-bGaB1jNVhCLLJgW11lfpvmcD2zA-Ns',
    appId: '1:798737752380:ios:817c330c6c22a392173e39',
    messagingSenderId: '798737752380',
    projectId: 'henry-store-94b54',
    storageBucket: 'henry-store-94b54.appspot.com',
    iosBundleId: 'com.henrystore.flutterStudy1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk-bGaB1jNVhCLLJgW11lfpvmcD2zA-Ns',
    appId: '1:798737752380:ios:882fcf7834d57f70173e39',
    messagingSenderId: '798737752380',
    projectId: 'henry-store-94b54',
    storageBucket: 'henry-store-94b54.appspot.com',
    iosBundleId: 'com.henrystore.flutterStudy1.RunnerTests',
  );
}
